"""Secondary dashboard pages that do not touch backend or agent logic."""

from datetime import datetime
import json

import streamlit as st


def save_completed_analysis() -> None:
    result = st.session_state.get("agent3_result")
    query = st.session_state.get("current_query")
    if not result or not query:
        return
    existing = st.session_state.get("saved_analyses", [])
    if any(item.get("query") == query for item in existing):
        return
    existing.insert(
        0,
        {
            "query": query,
            "created_at": datetime.now().strftime("%d %b %Y, %I:%M %p"),
            "candidates": getattr(result, "total_candidates_found", 0),
            "recommended": len(getattr(result, "ranked_sources", []) or []),
        },
    )
    st.session_state.saved_analyses = existing[:20]


def render_page_intro(title: str, subtitle: str) -> None:
    st.markdown(
        f"""
        <div class="page-intro">
            <h2>{title}</h2>
            <p>{subtitle}</p>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_previous_analyses() -> None:
    render_page_intro("Previous Analyses", "Recent dashboard sessions kept in this open app session.")
    analyses = st.session_state.get("saved_analyses", [])
    if not analyses:
        st.info("Completed analyses will appear here after the discovery pipeline finishes.")
        return
    for item in analyses:
        st.markdown(
            f"""
            <div class="analysis-row">
                <div>
                    <strong>{item['query']}</strong>
                    <span>{item['created_at']}</span>
                </div>
                <div class="analysis-stats">
                    <span>{item['candidates']} found</span>
                    <span>{item['recommended']} recommended</span>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )


def render_security_reports() -> None:
    render_page_intro("Security Reports", "Validation status for prompt safety, source quality, and retrieval readiness.")
    stage = st.session_state.get("pipeline_stage", "idle")
    checks = [
        ("Prompt Injection Guard", "Active", "User input is validated before Agent 1 runs."),
        ("Input Validation", "Active", "Scientific query text is normalized and checked."),
        ("Dataset Integrity", "Pending" if stage != "done" else "Ready", "Agent 4 verification hooks are represented in the UI."),
        ("Credential Isolation", "Active", "Frontend login is session-only and does not alter backend credentials."),
    ]
    cols = st.columns(4)
    for col, (name, status, detail) in zip(cols, checks):
        col.markdown(
            f"""
            <div class="security-card">
                <span>{status}</span>
                <strong>{name}</strong>
                <p>{detail}</p>
            </div>
            """,
            unsafe_allow_html=True,
        )


def render_download_center() -> None:
    render_page_intro("Download Center", "Export results and track retrieval assets from the current session.")
    result = st.session_state.get("agent3_result")
    if result is None:
        st.info("Run an analysis to enable result exports.")
        return
    payload = result.model_dump_json(indent=2)
    st.download_button(
        "Download Discovery Results",
        data=payload,
        file_name=f"earth_intelligence_discovery_{int(datetime.now().timestamp())}.json",
        mime="application/json",
        type="primary",
    )
    st.markdown("#### Available Artifacts")
    st.json(
        {
            "discovery_results": "ready",
            "dataset_files": "available after download execution",
            "security_report": "session summary visible in Security Reports",
        }
    )


def render_settings_page() -> None:
    render_page_intro("Settings", "Session preferences for the dashboard experience.")
    st.session_state.max_datasets = st.slider("Maximum Datasets", 3, 25, st.session_state.get("max_datasets", 10))
    st.session_state.enable_clarification = st.toggle(
        "Enable Clarification",
        value=st.session_state.get("enable_clarification", True),
    )
    st.session_state.show_reasoning = st.toggle(
        "Show Reasoning",
        value=st.session_state.get("show_reasoning", True),
    )
    st.session_state.dark_mode = st.toggle(
        "Dark Mode Preview",
        value=st.session_state.get("dark_mode", False),
    )
    if st.button("Save Settings", type="primary"):
        st.success("Settings saved for this session.")


def render_agent_outputs_page(render_agent1_panel, render_agent3_panel, render_dataset_detail) -> None:
    render_page_intro("Agent Outputs", "Structured outputs generated by the current multi-agent run.")
    if st.session_state.get("agent1_result"):
        render_agent1_panel(st.session_state.agent1_result)
    if st.session_state.get("agent3_result"):
        st.divider()
        render_agent3_panel(st.session_state.agent3_result)
        render_dataset_detail(st.session_state.agent3_result)
    if not st.session_state.get("agent1_result") and not st.session_state.get("agent3_result"):
        st.info("Agent outputs will appear here after you run an analysis.")


def render_pipeline_page(render_pipeline, render_logs) -> None:
    render_page_intro("Pipeline", "Live execution state for the scientific intelligence workflow.")
    render_pipeline()
    st.divider()
    render_logs()


def render_help_page() -> None:
    render_page_intro("Help", "A quick guide to using the platform.")
    st.markdown(
        """
        1. Open New Analysis and enter a scientific query.
        2. Review clarification prompts when the system needs more detail.
        3. Compare ranked datasets and inspect score breakdowns.
        4. Export discovery results from the Download Center.
        """
    )
